"""empty message

Revision ID: 77bca934a614
Revises: 
Create Date: 2024-03-11 18:11:35.588764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77bca934a614'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CPR_AED', sa.Boolean(), nullable=True,server_default='false'))
        batch_op.add_column(sa.Column('STB', sa.Boolean(), nullable=True,server_default='false'))
        batch_op.add_column(sa.Column('Narcan', sa.Boolean(), nullable=True,server_default='false'))
        batch_op.add_column(sa.Column('AHA_HS', sa.Boolean(), nullable=True,server_default='false'))
        batch_op.add_column(sa.Column('AHA_BLS', sa.Boolean(), nullable=True,server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('AHA_BLS')
        batch_op.drop_column('AHA_HS')
        batch_op.drop_column('Narcan')
        batch_op.drop_column('STB')
        batch_op.drop_column('CPR_AED')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
